sources:
  - name: raw
    description: Raw taxi trip data from NYC TLC
    database: |
      {%- if target.type == 'bigquery' -%}
        {{ env_var('GCP_PROJECT_ID', 'avid-task-486715-p7') }}
      {%- else -%}
        taxi_rides_ny
      {%- endif -%}
    schema: |
      {%- if target.type == 'bigquery' -%}
        data_engineering_zoomcamp_2026_nyc_taxi_dataset
      {%- else -%}
        prod
      {%- endif -%}
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    tables:
      - name: green_tripdata
        identifier: native_green
        description: Raw green taxi trip records
        loaded_at_field: pick_up_datetime
        columns:
          - name: vendor_id
            description: "Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.) - Note: Raw data may contain nulls, filtered in staging"
          - name: pick_up_datetime
            description: Date and time when the meter was engaged
          - name: drop_off_datetime
            description: Date and time when the meter was disengaged
          - name: passenger_count
            description: Number of passengers in the vehicle
          - name: trip_distance
            description: Trip distance in miles
          - name: pick_up_location_id
            description: TLC Taxi Zone where the meter was engaged
          - name: drop_off_location_id
            description: TLC Taxi Zone where the meter was disengaged
          - name: rate_code_id
            description: Rate code (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
          - name: store_and_forward_flag
            description: Trip record held in vehicle memory (Y/N)
          - name: payment_type
            description: Payment method (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)
          - name: fare_amount
            description: Time and distance fare
          - name: extra
            description: Miscellaneous extras and surcharges
          - name: mta_tax
            description: MTA tax
          - name: tip_amount
            description: Tip amount (credit card only)
          - name: tolls_amount
            description: Total tolls paid
          - name: improvement_surcharge
            description: Improvement surcharge
          - name: total_amount
            description: Total amount charged
          - name: trip_type
            description: Trip type (1=Street-hail, 2=Dispatch)
          - name: ehail_fee
            description: E-hail fee

      - name: yellow_tripdata
        identifier: native_yellow
        description: Raw yellow taxi trip records
        loaded_at_field: pick_up_datetime
        columns:
          - name: vendor_id
            description: "Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.) - Note: Raw data may contain nulls, filtered in staging"
          - name: pick_up_datetime
            description: Date and time when the meter was engaged
          - name: drop_off_datetime
            description: Date and time when the meter was disengaged
          - name: passenger_count
            description: Number of passengers in the vehicle
          - name: trip_distance
            description: Trip distance in miles
          - name: pick_up_location_id
            description: TLC Taxi Zone where the meter was engaged
          - name: drop_off_location_id
            description: TLC Taxi Zone where the meter was disengaged
          - name: rate_code_id
            description: Rate code (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
          - name: store_and_forward_flag
            description: Trip record held in vehicle memory (Y/N)
          - name: payment_type
            description: Payment method (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)
          - name: fare_amount
            description: Time and distance fare
          - name: extra
            description: Miscellaneous extras and surcharges
          - name: mta_tax
            description: MTA tax
          - name: tip_amount
            description: Tip amount (credit card only)
          - name: tolls_amount
            description: Total tolls paid
          - name: improvement_surcharge
            description: Improvement surcharge
          - name: total_amount
            description: Total amount charged
      - name: fhv_tripdata
        identifier: native_fhv
        description: Raw For-Hire Vehicle (FHV) trip records.
        loaded_at_field: pick_up_datetime
        columns:
          - name: dispatching_base_number
            description: "The TLC base license number that dispatched the trip"
          - name: pick_up_datetime
            description: "The date and time of the trip pickup"
          - name: drop_off_datetime
            description: "The date and time of the trip dropoff"
          - name: pick_up_location_id
            description: "TLC Taxi Zone ID where the trip began"
          - name: drop_off_location_id
            description: "TLC Taxi Zone ID where the trip ended"
          - name: shared_ride_flag
            description: "Indicates if the passenger shared the ride with others (1=Yes, 0=No)"
          - name: affiliated_base_number
            description: "The base number affiliated with the trip"