id: data_engineering_zoomcamp_2026_nyc_taxi_monthly_pipeline
namespace: company.nyc.taxi

inputs:
  - id: dataset_type
    type: SELECT
    values: [ "green", "yellow" , "fhv"]
    defaults: "green"
  - id: year
    type: SELECT
    values: [ "2019", "2020", "2021" ]
    defaults: "2019"
  - id: month
    type: SELECT
    values: [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" ]
    defaults: "01"


tasks:
  - id: download_file
    type: io.kestra.plugin.core.http.Download
    uri: "https://d37ci6vzurychx.cloudfront.net/trip-data/{{ inputs.dataset_type }}_tripdata_{{ inputs.year }}-{{ inputs.month }}.parquet"
    timeout: PT5M

  - id: delete_existing_file
    type: io.kestra.plugin.gcp.gcs.Delete
    uri: "gs://{{ envs.gcp_bucket_name }}/{{ inputs.dataset_type }}/{{ inputs.dataset_type }}_tripdata_{{ inputs.year }}-{{ inputs.month }}.parquet"
    errorOnMissing: false

  - id: upload_file_to_bucket
    type: "io.kestra.plugin.gcp.gcs.Upload"
    from: "{{ outputs.download_file.uri }}"
    to: "gs://{{ envs.gcp_bucket_name }}/{{ inputs.dataset_type }}/{{ inputs.dataset_type }}_tripdata_{{ inputs.year }}-{{ inputs.month }}.parquet"
    projectId: "{{ envs.gcp_project_id }}"

  - id: create_external_table
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: "{{ render(read('assets/silver/create_external_table.sql')) }}"

  - id: create_native_table
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: "{{ render(read('assets/init/create_table_' ~ inputs.dataset_type ~ '_if_not_exists.sql')) }}"

  - id: insert_into_native_table
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: "{{ render(read('assets/gold/delete_and_insert_into_' ~ inputs.dataset_type ~ '.sql')) }}"

  - id: drop_external_table
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: "{{ render(read('assets/teardown/drop_external_table.sql')) }}"

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
    timezone: America/New_York