id: data_engineering_zoomcamp_2026_nyc_taxi_monthly_pipeline
namespace: company.nyc.taxi

inputs:
  - id: dataset_type
    type: SELECT
    values: [ "green", "yellow" ]
    defaults: "green"
  - id: year
    type: SELECT
    values: [ "2019", "2020", "2021" ]
    defaults: "2019"
  - id: month
    type: SELECT
    values: [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" ]
    defaults: "1"
  - id: chunk_size
    type: INT
    defaults: 100000


tasks:
  - id: init
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "02-workflow-orchestration_default"
    containerImage: "{{ envs.init_stage_image_name }}"
    commands:
      - python -m init.main

  - id: silver
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "02-workflow-orchestration_default"
    containerImage: "{{ envs.silver_stage_image_name }}"
    commands:
      - python -m silver.main --dataset_type {{ inputs.dataset_type }} --year {{ inputs.year }} --month {{ inputs.month }} --chunk_size {{ inputs.chunk_size }}
    outputFiles:
      - "{{ envs.nyc_taxi_directory_path }}/*.parquet"
  - id: gold
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "02-workflow-orchestration_default"
    containerImage: "{{ envs.gold_stage_image_name }}"
    inputFiles:
      data.parquet: "{{ outputs.silver.outputFiles.values() | first }}"
    commands:
      - python -m gold.main --dataset_type {{ inputs.dataset_type }} --year {{ inputs.year }} --month {{ inputs.month }} --chunk_size {{ inputs.chunk_size }} --file_path data.parquet

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
    timezone: America/New_York